=== gaye-00/Cours-L2I-Promo-1/Semestre5/Formats_D'echanges_De_Donnees/TP/TP3/Exercice1.dtd
<!ELEMENT tableau (etudiant+)>
<!ELEMENT etudiant (nom, prenom, cc, examen, moy)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT examen (#PCDATA)>
<!ELEMENT moy (#PCDATA)>

=== gaye-00/Cours-L2I-Promo-1/Semestre5/Formats_D'echanges_De_Donnees/TP/TP3/Exercice1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tableau SYSTEM "Exercice1.dtd">
<tableau>
    <etudiant>
        <nom>BA</nom>
        <prenom>Moussa</prenom>
        <cc>12</cc>
        <examen>12</examen>
        <moy>12</moy>
    </etudiant>
      <etudiant>
        <nom>BALDE</nom>
        <prenom>Fatou</prenom>
        <cc>17</cc>
        <examen>16</examen>
        <moy>16.5</moy>
      </etudiant>
      <etudiant>
        <nom>DIALLO</nom>
        <prenom>Binetou</prenom>
        <cc>12</cc>
        <examen>10</examen>
        <moy>11</moy>
      </etudiant>
      <etudiant>
        <nom>DIALLO</nom>
        <prenom>Mamadou</prenom>
        <cc>15</cc>
        <examen>16</examen>
        <moy>15.5</moy>
      </etudiant>
      <etudiant>
        <nom>DIALLO</nom>
        <prenom>Mor</prenom>
        <cc>12</cc>
        <examen>10</examen>
        <moy>11</moy>
      </etudiant>
      <etudiant>
        <nom>FALL</nom>
        <prenom>Mouhamadou</prenom>
        <cc>17</cc>
        <examen>17</examen>
        <moy>17</moy>
      </etudiant>
      <etudiant>
        <nom>GNINGUE</nom>
        <prenom>Fatou</prenom>
        <cc>15</cc>
        <examen>18</examen>
        <moy>16.5</moy>
      </etudiant>
      <etudiant>
        <nom>NDIAYE</nom>
        <prenom>Ibrahima</prenom>
        <cc>16</cc>
        <examen>15</examen>
        <moy>15.5</moy>
      </etudiant>
      <etudiant>
        <nom>SAKHARE</nom>
        <prenom>Ousmane</prenom>
        <cc>16</cc>
        <examen>16</examen>
        <moy>16</moy>
      </etudiant>
      <etudiant>
        <nom>NIANG</nom>
        <prenom>Arame</prenom>
        <cc>15</cc>
        <examen>16</examen>
        <moy>15.5</moy>
      </etudiant>
      <etudiant>
        <nom>SOW</nom>
        <prenom>Mamy</prenom>
        <cc>15</cc>
        <examen>8</examen>
        <moy>11.5</moy>
      </etudiant>
      <etudiant>
        <nom>THIAM</nom>
        <prenom>Amy</prenom>
        <cc>17</cc>
        <examen>17</examen>
        <moy>17</moy>
      </etudiant>
      <etudiant>
        <nom>THIAW</nom>
        <prenom>Mamadou</prenom>
        <cc>17</cc>
        <examen>16</examen>
        <moy>16.5</moy>
      </etudiant>    
</tableau>
