=== gaye-00/Cours-L2I-Promo-1/Semestre5/Formats_D'echanges_De_Donnees/TP/TP3/repertoire.dtd
<!ELEMENT repertoire (categorie+)>
<!ELEMENT categorie (contact*)>
<!ATTLIST categorie nom CDATA #REQUIRED>
<!ELEMENT contact (bureau ,maison?)>
<!ATTLIST contact
    nom CDATA #REQUIRED
    prenom CDATA #REQUIRED>
<!ELEMENT bureau (#PCDATA)>
<!ATTLIST bureau
    telephone CDATA #REQUIRED
    adresse CDATA #REQUIRED
    courriel CDATA #IMPLIED
    fax CDATA #IMPLIED
    email CDATA #IMPLIED>
<!ELEMENT maison (#PCDATA)>
<!ATTLIST maison
    telephone CDATA #REQUIRED
    adresse CDATA #REQUIRED
    >


<!--  
    <!ELEMENT repertoire (categorie*)>
<!ELEMENT categorie (contact*)>
<!ATTLIST categorie
           nom  CDATA  #REQUIRED>
<!ELEMENT contact (bureau | maison )+>
<!ATTLIST contact
          nom CDATA #REQUIRED
          prenom CDATA #REQUIRED>
<!ELEMENT bureau (#PCDATA)>
<!ATTLIST bureau
          adresse CDATA #REQUIRED
          courriel CDATA #IMPLIED
          email CDATA #IMPLIED
          fax CDATA #IMPLIED
          telephone CDATA #REQUIRED>
<!ELEMENT maison (#PCDATA)>
<!ATTLIST maison
          adresse CDATA #REQUIRED
          telephone CDATA #REQUIRED >
 -->

=== gaye-00/Cours-L2I-Promo-1/Semestre5/Formats_D'echanges_De_Donnees/TP/TP3/Exercice2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE repertoire SYSTEM "repertoire.dtd">
<repertoire>
  <categorie nom="1-perso">
    <contact nom="desvignes" prenom="nicole">
      <bureau telephone="0234542312" adresse="2 rue de l'espoir 44566 Chignole" />
      <maison telephone="0870754566" adresse="2 rue de l'espoir 44566 Chignole" />
    </contact>
    <contact nom="fonteau" prenom="jeremie">
      <maison telephone="0445879044" adresse="6bis avenue Jean Charcot 65322 St Mazan" />
      <bureau telephone="0465345622" adresse="54 bd de la liberte 65444 jalibert">
        Batiment 6,Porte 5,Bureau 304
      </bureau>
    </contact>
  </categorie>
  <categorie nom="2-travail">
    <contact nom="martin" prenom="paul">
      <bureau telephone= "0245664442" adresse="5 rue de l'epine 45665 Astorie" courriel="paul.martin@gmail.com" fax="0245664412" />
    </contact>
    <contact nom="batiset" prenom="raymond">
      <bureau telephone="0248666445" adresse="5 rue de l'epine 45665 Astorie" courriel="rbatisset@free.fr" />
    </contact>
    <contact nom="fonteau" prenom="paul">
      <bureau telephone="0345678966" adresse="34 chemin de la fraise 56789 Gheno" email="paul-fonteau@yahoo.fr" />
      <maison telephone="0256780032" adresse="11 rue du petit plaisir 56888Trigonet" />
    </contact>
  </categorie>
</repertoire>
